// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cbsStudents.Data;
#nullable disable

namespace CbsStudentsDotnet.Migrations
{
    [DbContext(typeof(CbsStudentContext))]
    [Migration("20220328072814_SeededDb")]
    partial class SeededDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("cbsStudents.Models.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            PostId = 1,
                            Text = "This is a comment on post 1",
                            TimeStamp = new DateTime(2022, 3, 28, 9, 28, 14, 554, DateTimeKind.Local).AddTicks(3030)
                        },
                        new
                        {
                            CommentId = 2,
                            PostId = 1,
                            Text = "This is also a comment on post 1",
                            TimeStamp = new DateTime(2022, 3, 28, 9, 28, 14, 554, DateTimeKind.Local).AddTicks(3170)
                        },
                        new
                        {
                            CommentId = 3,
                            PostId = 2,
                            Text = "This is a comment on post 2",
                            TimeStamp = new DateTime(2022, 3, 28, 9, 28, 14, 554, DateTimeKind.Local).AddTicks(3190)
                        },
                        new
                        {
                            CommentId = 4,
                            PostId = 2,
                            Text = "This is also a comment on post 2",
                            TimeStamp = new DateTime(2022, 3, 28, 9, 28, 14, 554, DateTimeKind.Local).AddTicks(3200)
                        },
                        new
                        {
                            CommentId = 5,
                            PostId = 3,
                            Text = "This is a comment on post 3",
                            TimeStamp = new DateTime(2022, 3, 28, 9, 28, 14, 554, DateTimeKind.Local).AddTicks(3210)
                        },
                        new
                        {
                            CommentId = 6,
                            PostId = 3,
                            Text = "This is also a comment on post 3",
                            TimeStamp = new DateTime(2022, 3, 28, 9, 28, 14, 554, DateTimeKind.Local).AddTicks(3350)
                        });
                });

            modelBuilder.Entity("cbsStudents.Models.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmountOfComments")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmountOfLikes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Media")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountOfComments = 7,
                            AmountOfLikes = 5,
                            Created = new DateTime(2022, 3, 28, 9, 28, 14, 554, DateTimeKind.Local).AddTicks(290),
                            Media = "Image",
                            Status = 0,
                            Text = "This is the description of my first post",
                            Title = "This is my first post"
                        },
                        new
                        {
                            Id = 2,
                            AmountOfComments = 12,
                            AmountOfLikes = 10,
                            Created = new DateTime(2022, 3, 28, 9, 28, 14, 554, DateTimeKind.Local).AddTicks(1110),
                            Media = "Video",
                            Status = 0,
                            Text = "This is the description of my second post",
                            Title = "This is my second post"
                        },
                        new
                        {
                            Id = 3,
                            AmountOfComments = 1,
                            AmountOfLikes = 3,
                            Created = new DateTime(2022, 3, 28, 9, 28, 14, 554, DateTimeKind.Local).AddTicks(1130),
                            Media = "Image",
                            Status = 0,
                            Text = "This is the description of my third post",
                            Title = "This is my third post"
                        });
                });

            modelBuilder.Entity("cbsStudents.Models.Entities.Comment", b =>
                {
                    b.HasOne("cbsStudents.Models.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("cbsStudents.Models.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
